import React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { EodReportEntity } from '@ems/shared-types';
import { CheckCircle2, Clock, Sparkles, XCircle, AlertCircle } from 'lucide-react';

interface EodCardProps {
  report: EodReportEntity;
  onReview?: (report: EodReportEntity) => void;
  isManagerView?: boolean;
}

export function EodCard({ report, onReview, isManagerView }: EodCardProps) {
  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'APPROVED': return <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800"><CheckCircle2 className="w-3 h-3 mr-1" /> Approved</span>;
      case 'REJECTED': return <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-red-100 text-red-800"><XCircle className="w-3 h-3 mr-1" /> Rejected</span>;
      case 'AUTO_GENERATED': return <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800"><AlertCircle className="w-3 h-3 mr-1" /> Auto Generated</span>;
      case 'SUBMITTED': return <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800"><Clock className="w-3 h-3 mr-1" /> Pending</span>;
      default: return <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800">{status}</span>;
    }
  };

  const getProductivityColor = (score: number | null) => {
    if (!score) return 'text-gray-500';
    if (score >= 90) return 'text-green-600';
    if (score >= 70) return 'text-yellow-600';
    return 'text-red-600';
  };

  return (
    <Card className="w-full transition-all hover:shadow-md border-sidebar-border">
      <CardHeader className="pb-3">
        <div className="flex justify-between items-start">
          <div>
            <CardTitle className="text-lg font-semibold flex items-center gap-2">
              EOD Report - {new Date(report.date).toLocaleDateString()}
            </CardTitle>
            {isManagerView && report.employee && (
              <p className="text-sm text-muted-foreground mt-1">
                {report.employee.user?.firstName} {report.employee.user?.lastName}
              </p>
            )}
          </div>
          {getStatusBadge(report.status)}
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* AI Summary Section */}
        {report.aiSummary && (
          <div className="bg-brand-50/50 rounded-lg p-4 border border-brand-100">
            <div className="flex items-center gap-2 mb-2 text-brand-700 font-medium">
              <Sparkles className="w-4 h-4" />
              <span>AI Summary</span>
            </div>
            <p className="text-sm text-gray-700 leading-relaxed">
              {report.aiSummary}
            </p>
          </div>
        )}

        {/* Detailed Info (if manually submitted and not just AI summary) */}
        {!report.isAutoGenerated && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm mt-4">
            {report.tasksWorkedOn && (
              <div>
                <span className="font-semibold text-gray-700">Tasks Worked On:</span>
                <p className="text-gray-600 mt-1">{report.tasksWorkedOn}</p>
              </div>
            )}
            {report.tomorrowPlan && (
              <div>
                <span className="font-semibold text-gray-700">Plan for Tomorrow:</span>
                <p className="text-gray-600 mt-1">{report.tomorrowPlan}</p>
              </div>
            )}
            {report.challengesFaced && (
              <div className="col-span-full">
                <span className="font-semibold text-gray-700">Challenges Faced:</span>
                <p className="text-gray-600 mt-1">{report.challengesFaced}</p>
              </div>
            )}
          </div>
        )}

        <div className="flex items-center justify-between pt-4 border-t border-gray-100">
          <div className="flex items-center gap-4 text-sm">
            <div className="flex items-center gap-1.5 text-gray-600">
              <Clock className="w-4 h-4" />
              <span>{report.hoursSpent || 0} Hours</span>
            </div>
            {report.productivityScore && (
              <div className="flex items-center gap-1.5 font-medium">
                <span className="text-gray-600">Productivity:</span>
                <span className={getProductivityColor(report.productivityScore)}>
                  {report.productivityScore}%
                </span>
              </div>
            )}
          </div>
        </div>
      </CardContent>
      {isManagerView && (report.status === 'SUBMITTED' || report.status === 'AUTO_GENERATED') && (
        <CardFooter className="pt-0 justify-end">
          <Button variant="outline" size="sm" onClick={() => onReview && onReview(report)}>
            Review Report
          </Button>
        </CardFooter>
      )}
    </Card>
  );
}
