import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { PrismaService } from '../../database/prisma.service';
import { EodService } from './eod.service';
import { NotificationsService } from '../notifications/notifications.service';

@Injectable()
export class EodCronService {
  private readonly logger = new Logger(EodCronService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly eodService: EodService,
    private readonly notificationsService: NotificationsService,
  ) {}

  // 1. First Reminder at 6:00 PM
  @Cron('0 18 * * 1-5') // Mon-Fri at 18:00
  async handleFirstReminder() {
    this.logger.log('Running First EOD Reminder (6:00 PM)');
    await this.sendRemindersToPendingEmployees('Please submit your EOD report. It is due soon.', 'MEDIUM');
  }

  // 2. Second Reminder at 7:00 PM
  @Cron('0 19 * * 1-5')
  async handleSecondReminder() {
    this.logger.log('Running Second EOD Reminder (7:00 PM)');
    await this.sendRemindersToPendingEmployees('EOD report is still pending. Please submit it.', 'HIGH');
  }

  // 3. Final Reminder at 8:00 PM
  @Cron('0 20 * * 1-5')
  async handleFinalReminder() {
    this.logger.log('Running Final EOD Reminder (8:00 PM)');
    await this.sendRemindersToPendingEmployees('Auto-generated EOD will be submitted at 9:00 PM if you do not submit one manually.', 'CRITICAL');
  }

  // 4. Auto Generation at 9:00 PM
  @Cron('0 21 * * 1-5')
  async handleAutoGeneration() {
    this.logger.log('Running Auto EOD Generation (9:00 PM)');
    const pendingEmployees = await this.getPendingEmployees();
    
    for (const employee of pendingEmployees) {
      try {
        await this.eodService.generateAutoEod(employee.id);
        
        // Notify the user it was auto-generated
        await this.notificationsService.create({
          userId: employee.userId,
          title: 'EOD Auto-Generated',
          message: 'Your EOD report for today was automatically generated by the system.',
          type: 'SYSTEM' as any,
          priority: 'MEDIUM' as any,
        });
      } catch (error) {
        this.logger.error(`Failed to auto-generate EOD for employee ${employee.id}:`, error);
      }
    }
  }

  private async getPendingEmployees() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Find all active employees who haven't submitted an EOD today
    const employees = await this.prisma.employee.findMany({
      where: {
        status: 'ACTIVE',
        eodReports: {
          none: {
            date: { gte: today },
            status: { not: 'DRAFT' } // Ignore drafts, count them as pending
          }
        }
      },
      select: { id: true, userId: true }
    });

    return employees;
  }

  private async sendRemindersToPendingEmployees(message: string, priority: string) {
    const pending = await this.getPendingEmployees();
    
    for (const employee of pending) {
      await this.notificationsService.create({
        userId: employee.userId,
        title: 'EOD Reminder',
        message,
        type: 'SYSTEM' as any,
        priority: priority as any,
      });
    }
  }
}
