import { Injectable, Logger, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import { PaginationDto } from '../../common/dto/pagination.dto';
import { EodStatus } from '@ems/shared-types';

@Injectable()
export class EodService {
  private readonly logger = new Logger(EodService.name);

  constructor(private readonly prisma: PrismaService) {}

  private async getEmployeeId(userId: string): Promise<string> {
    const employee = await this.prisma.employee.findUnique({ where: { userId } });
    if (!employee) throw new NotFoundException('Employee profile not found');
    return employee.id;
  }

  async findAll(pagination: PaginationDto) {
    const { skip, limit } = pagination;
    const [items, total] = await Promise.all([
      this.prisma.eodReport.findMany({
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: {
          employee: {
            include: { user: { select: { firstName: true, lastName: true, avatar: true } } }
          },
          project: { select: { name: true, key: true } },
        },
      }),
      this.prisma.eodReport.count(),
    ]);

    return {
      items,
      meta: {
        total,
        page: pagination.page,
        limit,
        totalPages: Math.ceil(total / limit),
        hasNextPage: pagination.page * limit < total,
        hasPreviousPage: pagination.page > 1,
      },
    };
  }

  async findByEmployee(userId: string, pagination: PaginationDto) {
    const employeeId = await this.getEmployeeId(userId);
    const { skip, limit } = pagination;
    const [items, total] = await Promise.all([
      this.prisma.eodReport.findMany({
        where: { employeeId },
        skip,
        take: limit,
        orderBy: { date: 'desc' },
        include: { project: { select: { name: true, key: true } } },
      }),
      this.prisma.eodReport.count({ where: { employeeId } }),
    ]);

    return { items, meta: { total, page: pagination.page, limit } };
  }

  async checkTodaySubmission(userId: string) {
    const employeeId = await this.getEmployeeId(userId);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const report = await this.prisma.eodReport.findFirst({
      where: {
        employeeId,
        date: { gte: today },
      },
    });

    return { submitted: !!report, report };
  }

  async submitManualEod(userId: string, data: any) {
    const employeeId = await this.getEmployeeId(userId);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Check if already submitted today
    const existing = await this.prisma.eodReport.findFirst({
      where: { employeeId, date: { gte: today } },
    });

    if (existing && existing.status !== 'DRAFT') {
      throw new BadRequestException('EOD for today is already submitted.');
    }

    // Generate AI Summary (Mock heuristic for Phase 1)
    const mockAiSummary = `Today, the employee focused on ${data.tasksWorkedOn || 'various tasks'}. ${data.description ? 'They noted: ' + data.description : ''} Total active work time was ${data.hoursSpent || 0} hours.`;

    // Productivity score (heuristic out of 100)
    const productivityScore = Math.min(100, Math.floor(((data.hoursSpent || 0) / 8) * 100));

    if (existing) {
      return this.prisma.eodReport.update({
        where: { id: existing.id },
        data: {
          ...data,
          status: 'SUBMITTED',
          aiSummary: mockAiSummary,
          productivityScore,
        },
      });
    }

    return this.prisma.eodReport.create({
      data: {
        employeeId,
        date: new Date(),
        ...data,
        status: 'SUBMITTED',
        isAutoGenerated: false,
        aiSummary: mockAiSummary,
        productivityScore,
      },
    });
  }

  async reviewEod(id: string, managerUserId: string, status: string, comments?: string) {
    const managerId = await this.getEmployeeId(managerUserId);
    const report = await this.prisma.eodReport.findUnique({ where: { id } });
    if (!report) throw new NotFoundException('EOD Report not found');

    return this.prisma.eodReport.update({
      where: { id },
      data: {
        status: status as EodStatus,
        managerId,
        managerComments: comments,
        reviewedAt: new Date(),
      },
    });
  }

  // Used by Cron Service
  async generateAutoEod(employeeId: string) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    // Fetch activities
    const attendances = await this.prisma.attendance.findMany({
      where: { employeeId, date: { gte: today } },
    });
    
    // In a real app, query tasks worked on or updated today
    const tasks = await this.prisma.task.findMany({
      where: { assignedTo: employeeId, updatedAt: { gte: today } },
    });

    const hoursSpent = attendances.reduce((acc, curr) => acc + (Number(curr.totalHours) || 0), 0) || 8; // Default 8 if no attendance found
    const tasksWorkedOn = tasks.map(t => t.title).join(', ') || 'General maintenance and meetings';

    const mockAiSummary = `Automatically generated summary: Employee worked on ${tasksWorkedOn}. Logged hours: ${hoursSpent}.`;

    return this.prisma.eodReport.create({
      data: {
        employeeId,
        date: new Date(),
        tasksWorkedOn,
        description: 'Auto-generated system report due to missed manual submission.',
        hoursSpent,
        status: 'AUTO_GENERATED',
        isAutoGenerated: true,
        aiSummary: mockAiSummary,
        productivityScore: Math.min(100, Math.floor((hoursSpent / 8) * 80)), // Penalize auto slightly
      },
    });
  }
}
